apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: loadxucr8716-tenant-component
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: loadxucr8716-tenant-component
    app.kubernetes.io/part-of: loadxucr8716-tenant-app
  name: loadxucr8716-tenant-component
  namespace: loadxucr8716-tenant
spec:
  path: /
  port:
    targetPort: 8081
  to:
    kind: Service
    name: loadxucr8716-tenant-component
    weight: null
status: {}
